name: Tests

on: [push]

jobs:
  model-controller-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install Gems
        run: gem install bundler
      - name: Run Bundlenstall
        run: bundle install
      - name: Run Model Controller Tests
        run: bundle exec rails test
